-- ============================================================
-- Tennis Explore - Unstructured Data Schema
-- PostgreSQL 16
--
-- Purpose:
-- Stores metadata and extracted text chunks produced by the
-- Tennis Explore unstructured-data production pipeline.
--
-- Original PDF/PPTX files remain in their source storage
-- (for example AWS S3). They are NOT stored in PostgreSQL.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Create schema
-- ------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS unstructured;


-- ------------------------------------------------------------
-- 2. Documents
-- ------------------------------------------------------------
-- One row represents one source document.
--
-- resource_id is the stable identifier created by the
-- production ingestion pipeline.
--
-- The table also records processing/extraction/chunking status
-- so documents requiring OCR, failed source files, and
-- successfully processed zero-chunk documents remain visible.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS unstructured.documents (

    document_id BIGSERIAL PRIMARY KEY,

    resource_id VARCHAR(64) NOT NULL UNIQUE,

    source_system VARCHAR(50) NOT NULL,

    source_location TEXT NOT NULL,

    file_name TEXT NOT NULL,

    file_type VARCHAR(20) NOT NULL,

    size_bytes BIGINT,

    etag TEXT,

    last_modified TIMESTAMPTZ,

    processing_status VARCHAR(50),

    extraction_status VARCHAR(50),

    chunking_status VARCHAR(50),

    chunk_count INTEGER NOT NULL DEFAULT 0,

    processed_at TIMESTAMPTZ,

    requires_ocr BOOLEAN NOT NULL DEFAULT FALSE,

    error_type TEXT,

    error_message TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ------------------------------------------------------------
-- 3. Document chunks
-- ------------------------------------------------------------
-- One document can contain many chunks.
--
-- source_chunk_id preserves the chunk identifier generated by
-- the unstructured-data chunking pipeline.
--
-- Embeddings are intentionally NOT stored yet.
-- Vector storage will be added after the team confirms whether
-- pgvector will be enabled in the shared PostgreSQL database.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS unstructured.document_chunks (

    chunk_db_id BIGSERIAL PRIMARY KEY,

    document_id BIGINT NOT NULL,

    source_chunk_id TEXT NOT NULL,

    chunk_index INTEGER NOT NULL,

    page_number INTEGER,

    slide_number INTEGER,

    chunk_text TEXT NOT NULL,

    word_count INTEGER,

    character_count INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_document_chunks_document
        FOREIGN KEY (document_id)
        REFERENCES unstructured.documents(document_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_document_source_chunk
        UNIQUE (document_id, source_chunk_id)
);


-- ------------------------------------------------------------
-- 4. Indexes
-- ------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_documents_resource_id
    ON unstructured.documents(resource_id);

CREATE INDEX IF NOT EXISTS idx_documents_source_system
    ON unstructured.documents(source_system);

CREATE INDEX IF NOT EXISTS idx_documents_processing_status
    ON unstructured.documents(processing_status);

CREATE INDEX IF NOT EXISTS idx_documents_extraction_status
    ON unstructured.documents(extraction_status);

CREATE INDEX IF NOT EXISTS idx_documents_chunking_status
    ON unstructured.documents(chunking_status);

CREATE INDEX IF NOT EXISTS idx_document_chunks_document_id
    ON unstructured.document_chunks(document_id);

CREATE INDEX IF NOT EXISTS idx_document_chunks_source_chunk_id
    ON unstructured.document_chunks(source_chunk_id);


-- ------------------------------------------------------------
-- 5. Future vector extension
-- ------------------------------------------------------------
-- pgvector has NOT yet been confirmed for the team's shared
-- PostgreSQL environment.
--
-- If pgvector is approved later, the following can be added
-- through a future database migration:
--
-- CREATE EXTENSION IF NOT EXISTS vector;
--
-- ALTER TABLE unstructured.document_chunks
-- ADD COLUMN embedding vector(384);
--
-- 384 corresponds to the current embedding model:
-- sentence-transformers/all-MiniLM-L6-v2
-- ------------------------------------------------------------